openapi: 3.0.0
info:
  title: Review Spark Gather API
  version: 1.0.0
  description: API for managing employee reviews and feedback

paths:
  /api/reviews:
    get:
      summary: Get all reviews
      parameters:
        - name: page
          in: query
          schema:
            type: integer
            default: 1
        - name: limit
          in: query
          schema:
            type: integer
            default: 10
        - name: status
          in: query
          schema:
            type: string
            enum: [pending, approved, rejected]
      responses:
        '200':
          description: List of reviews
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Review'
                  pagination:
                    $ref: '#/components/schemas/Pagination'

components:
  schemas:
    Review:
      type: object
      properties:
        id:
          type: string
        content:
          type: string
        rating:
          type: integer
          minimum: 1
          maximum: 5
        employee_id:
          type: string
        created_at:
          type: string
          format: date-time
        status:
          type: string
          enum: [pending, approved, rejected]