// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

// const SUPABASE_URL = "https://uiszftfrxbqjqdgybbmk.supabase.co";
// const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVpc3pmdGZyeGJxanFkZ3liYm1rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NzU2OTMsImV4cCI6MjA2NTU1MTY5M30.cqwmP1AraNOdW97R8zdzBu92tYBzTNKPjEQo7Wgx6PA";

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY
);
